package GestioneMagazzino;

import javax.swing.*;
import java.awt.*;

public class caricafarm {
	private JPanel framePnl;
	private JTextField nomeF;
	private JTextField qta;
	private JTextField scadenza;
	private JLabel qtaLbl;
	private JLabel nomeLbl;
	private JLabel scadenzaLbl;
	private JButton notificheButton;
	private JButton logoutButton;
	private JPanel headerPnl;
	private JPanel notifichePnl;
	private JPanel farmaciaPnl;
	private JLabel farmaciaLbl;
	private JPanel LogoutPanel;
	private JPanel mainPnl;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		framePnl = new JPanel();
		framePnl.setLayout(new BorderLayout(0, 0));
		mainPnl = new JPanel();
		mainPnl.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		mainPnl.setEnabled(true);
		framePnl.add(mainPnl, BorderLayout.CENTER);
		nomeLbl = new JLabel();
		nomeLbl.setText("Nome");
		mainPnl.add(nomeLbl);
		nomeF = new JTextField();
		nomeF.setColumns(25);
		nomeF.setText("");
		mainPnl.add(nomeF);
		qtaLbl = new JLabel();
		qtaLbl.setText("Quantità");
		mainPnl.add(qtaLbl);
		qta = new JTextField();
		qta.setColumns(5);
		mainPnl.add(qta);
		scadenzaLbl = new JLabel();
		scadenzaLbl.setText("Scadenza");
		mainPnl.add(scadenzaLbl);
		scadenza = new JTextField();
		mainPnl.add(scadenza);
		headerPnl = new JPanel();
		headerPnl.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		framePnl.add(headerPnl, BorderLayout.NORTH);
		notifichePnl = new JPanel();
		notifichePnl.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
		headerPnl.add(notifichePnl);
		notificheButton = new JButton();
		notificheButton.setText("Notifiche");
		notifichePnl.add(notificheButton);
		farmaciaPnl = new JPanel();
		farmaciaPnl.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		headerPnl.add(farmaciaPnl);
		farmaciaLbl = new JLabel();
		farmaciaLbl.setText("Farmacia");
		farmaciaPnl.add(farmaciaLbl);
		LogoutPanel = new JPanel();
		LogoutPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
		headerPnl.add(LogoutPanel);
		logoutButton = new JButton();
		logoutButton.setText("Logout");
		LogoutPanel.add(logoutButton);
	}
	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return framePnl;
	}
}
